### PR TITLE
v0.2.0 - Minor Release

### PR DESCRIPTION
**Pull request by Duroktar**
### Hot Reloading

Turn on Hot Mode to enable live reloading of code as you work. You can set the
minimum frequency from the user settings if you want more control over when your
file is saved/run.

_Turn on Live Reloading:_

    "wolf.hot": true

Adjust minimum time between saves (throttle control) in milliseconds:

    "wolf.hotFrequency": 270

> Note: Frequency setting is clamped between 100 and 1000 millisecends

### Macros are Back

A comment macro is any single line comment character (pound/hash symbol)
followed by a question mark. See the examples above to get a better idea
of how they work, and check out the macro syntax rules below.

Syntax:

    some.expression()           #?  <----Comment Macro
    a = [i for i in some_list]  # ?  <----Space allowed

> Note: Macros are restricted on lines starting with these
> blacklisted tokens.

* continue
* pass
* return
* if
* for
* while

  return 0 #? <---Restriced, won't work

### Completely Rewritten Codebase

Efforts have been made to improve the structure of the core Wolf
extension to allow for easier updates and more powerful features
in the future.

### ReWritten Sticky Logic

Wolf now uses the builtin API for improving the sticky behavior of
line decorations, especially while coding with Hot Reloading turned
off.

### Overview Ruler Markers

Annotated lines now show up in the OverView ruler panel on the left side
and are color coded for easy visual grepping.

### Hover Information

Hover over any Wolf annotation to see the value pretty printed in a
popup box.

### CODE REVIEW

**Comment by Almenon** [comment]
You might want to turn hot mode on by default - if it's locked away in a setting most users are not going to realize it is even there.  Similar to VSCode's autosave - you can autosave after a delay but it is turned off by default.

Also I really like the pawprint icons rather than the wolf icon, I would suggest making that the default.

The popup box is a good addition, nice work.

**Comment by Duroktar** [comment]
@Almenon 

> You might want to turn hot mode on by default

I'd love to! The only concern I have is someone will have it running while importing and setting up
http requests without using a cache or something. I'd hate to see an API get slammed with requests because of Wolf (or even get a user blocked from said API). But maybe I'm being over cautious; I basically run Wolf now with Hot Mode enabled all the time, and it _is_ much more enjoyable.

> Also I really like the pawprint icons rather than the wolf icon, I would suggest making that the default.

Agreed! Consider it done for the next patch release.

> The popup box is a good addition, nice work.

Thanks! I'm still not happy with the formatting though, I'm using `pprint.pformat`. But I think I may do a check if the user has Prettify or Beautifier installed first and pretty print the output with that. IMO those formatters do a better job.

> Live Reloading

Yeah, that part was tough. I think I can use a Virtual Editor to achieve the same effect without having to continuously save the file. But for now the method I have seems to work! Feel free to use the throttling function from here on AREPL if it helps. (AREPL is pretty cool BTW, I was trying it out and you did a damn good job. Kudos.)

Cheers :beers:

**Comment by Almenon** [comment]
> Thanks! I'm still not happy with the formatting though, I'm using pprint.pformat. But I think I may do a check if the user has Prettify or Beautifier installed first and pretty print the output with that. IMO those formatters do a better job.

I would suggest formatting it on the JS side - that way you keep the 'view' seperate from the buisiness logic.  In AREPL I use [renderJSON](https://github.com/caldwell/renderjson) but there are other libraries as well.

https://github.com/Almenon/AREPL-vscode/blob/master/media/jsonRenderer.js

https://github.com/Almenon/AREPL-vscode/blob/01e3b4c4bd267642bc638b84b57ba4c8ca0c2b49/src/HTMLDocumentContentProvider.ts#L93

Another thing you might want to consider is packaging your python dependencies with the extension.  In [arepl-backend](https://github.com/Almenon/AREPL-backend/tree/master/python/jsonpickle) I just put jsonpickle into a folder.  This has three benefits:

1. Version control - I am using a version I know works rather than a new version that could break things
2. simplicity - no need for custom logic to tell user to install package
3. ease of use - user does not have to install anything extra

The downside, of course, is that you have to maintain the package yourself.  So it's really up to you which option you want to pick.

**Comment by Duroktar** [comment]
> In AREPL I use renderJSON

Awesome, I'll look into that one, thanks! I agree with you about separating the logic out from the view so I think that's the way to go.

> Another thing you might want to consider is packaging your python dependencies with the extension. 

I don't think hunter has been updated since around last October or so. So packaging it up with Wolf is a good idea and probably feasible. The only thing is: it uses c_types in a few modules so that may be a hurdle but I'm just guessing (it may be no problem at all).

P.S.  I've got another patch I'm just getting ready to push now. Its got most the changes you suggested earlier (no need to restart after changing config, and pawprints and hot mode on by default)  😃

**Comment by Duroktar** [comment]
The changes mentioned earlier are now live and ready to go! Let me know if you find any bugs, and thanks again for the suggestions. 🍻

**Comment by Almenon** [comment]
Welcome.  BTW for the throttling you might want to use VSCode's throttling implmentation - they put in in a decorator so it is just a one line call.

https://github.com/Microsoft/vscode/blob/ca58c21bfc2f8e1a1f6f09667402d58d3dafe7d0/extensions/git/src/decorators.ts

**Pull request merged**
